### ISSUE TITLE
Use MPU to protect applications

### ISSUE THREAD

**Issue by alevy** [helena-project/tock#24]
Need to actually enforce memory protection to allow applications access to their own memory and code, but nothing else (including memory lent to the kernel).

### Memory Layout

Application memory is already laid out to support protection. The application code section lives in one of the `.app.N` sections. The application memory lives in a discreet element of `process::MEMORIES` and `process::Process#exposed_memory_start` notes the location memory (within the bounds of the application's memory) where exposed memory begins.

### Cortex-M4 MPU

The `sam4l` supports the ARM MPU extension, allowing up to 8 potentially overlapping regions, and up to 8 sub-regions (depending on the size of a region).

Isolating applications with the MPU should be simply defined in three regions:

  1. A base region that covers all of memory and turns off all access.

  2. A region for the application code section, marked read and execute (not write).

  3. A region for the application memory marked read/write/execute.

### NRF51 MPU

The NRF51 MPU works differently. There only two memory regions, and two code regions with pre-defined access control.

Need to investigate how to best use this mechanism to isolate an app. Luckily, we likely only want to fit a single app on the NRF51 anyway.

## Tasks

  - [x] Implement MPU for Cortex-M4

  - [ ] Investigate how to use the NRF51 MPU

  - [x] Make interface for protecting an application hardware-agnostic (e.g. an api call into the chip implementation).

**Comment by alevy** [comment]
Resolved in #65
