### ISSUE TITLE
FXOS8700CQ (Accelerometer + Magnetometer) Driver

### ISSUE THREAD

**Issue by alevy** [helena-project/tock#27]
A driver on top of I2C for the the FXOS8700CQ accelerometer and magnetometer driver.
## Tasks
- [x] Basic accelerometer operation modelled off the TMP006 driver (using a timer)
- [x] Basic magnetometer operation
- [ ] Provide access to both accel and magnetometer readings at once

**Comment by alevy** [comment]
This is actually blocking on a reimplementation of the `I2C` driver.
