### ISSUE TITLE
nRF51822: Implement timer support

### ISSUE THREAD

**Issue by lizardo** [helena-project/tock#29]
Initial user for timers will be the sample "c_blinky" app.

## Tasks
- [x] Implement basic interrupt support (fix ISR vector, NVIC etc.)
- [x] Implement Alarm interface for at least one hardware timer (nRF51822 has 3 high-frequency TIMERs + 2 low-frequency RTCs), like src/chips/sam4l/ast.rs
- [x] Implement platform support in src/platform/nrf_pca10001/lib.rs
- [x] Abstract GPIO pin assignment for LED on application library
